name: Deploy Project to App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test and Sonarqube
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GCS_KEY_BASE64: ${{ secrets.GCS_KEY_BASE64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Test & analyze
        run: ./gradlew test jacocoTestReport sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    needs: test # It's good practice to uncomment this once 'test' job is stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject secret keys into app.yaml
        run: |
          # Ensure the placeholders in app.yaml are exactly 'OPENAI_API_KEY: ""' and 'GCS_KEY_BASE64: ""'
          # We use '#' as the sed delimiter to avoid conflicts with characters in the secrets.
          # The outer single quotes '...' for the sed command protect special characters from shell interpretation.
          # The inner double quotes "..." around the secret ensure the value is correctly quoted in the YAML.

          echo "Attempting to substitute OPENAI_API_KEY..."
          sed -i 's#OPENAI_API_KEY: ""#OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"#g' app.yaml

          echo "Attempting to substitute GCS_KEY_BASE64..."
          sed -i 's#GCS_KEY_BASE64: ""#GCS_KEY_BASE64: "${{ secrets.GCS_KEY_BASE64 }}"#g' app.yaml

          echo "--- app.yaml content after substitution ---"
          cat app.yaml
          echo "-----------------------------------------"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2 # Consider using v2 or latest stable
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_CREDENTIALS }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2 # Consider using v2 or latest stable
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT_ID }}
