name: Deploy Project to App Engine (Simplified Secrets)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Optional: Keep your 'test' job if you have one

  deploy:
    name: Deploying to Google Cloud (Simplified Auth)
    runs-on: ubuntu-latest
    # needs: test # Optional: Uncomment if you have a test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate using Service Account Key JSON (Less Secure Method)
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_CREDENTIALS }}' # Use the SA Key secret

      # Set up Cloud SDK (gcloud CLI)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy and Set Secret Env Var
        run: |-
          gcloud app deploy app.yaml --quiet \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars=OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
        # '--set-env-vars' injects the GitHub Secret into the App Engine runtime environment